id: I5062832A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-26T10:06:46+00:00'
last_modified: '2022-06-14T08:18:59.883819+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294727
  title: ཞི་བྱེད་དང་གཅོད་ཡུལ་སོགས་གདམས་ངག་ཐོར་བུའི་ཆོས་སྐོར།
  author: ''
  base:
    6CCE:
      image_group_id: I8LS24006
      title: ''
      total_pages: ''
      order: 1
      base_file: 6CCE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
